@startuml

Client -> AuthorizationServer:1.GET Authentication Token Request
AuthorizationServer --> Client:2.Return Token Response

Client -> ResourceServer:3. Api Request
ResourceServer --> Client:4. Return Data Response

Client -> AuthorizationServer:5. Refresh Authentication Token Request
AuthorizationServer --> Client:6. Return Token Response

@enduml